name: TestRunner

on:
  push:
    branches:
    - master

jobs:
  createDllJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2018.4.9f1]
    steps:
    - name: Create Directory & Git Clone & Checkout & Remove Test Folder & Copy Files
      run: |
        mkdir artifact
        mkdir artifact_unity
        mkdir artifact_setting
        git clone https://github.com/pCYSl5EDgo/UniNativeLinq-EditorExtension-Test
        cd UniNativeLinq-EditorExtension-Test # UniNativeLinq-EditorExtension-Test
        git config --local user.name "pCYSl5EDgo"
        git config --local user.email "pCYSl5EDgo@yahoo.co.jp"
        git checkout $GITHUB_SHA
        cd Assets # UniNativeLinq-EditorExtension-Test/Assets
        cp Tests.meta ../../
        rm -f Tests.meta
        rm -rf Tests
        cd .. # UniNativeLinq-EditorExtension-Test
        openssl aes-256-cbc -d -in Unity_v2018.x.ulf-cipher -k ${CYPHER_KEY} >> Unity_v2018.x.ulf
        /opt/Unity/Editor/Unity -logFile -manualLicenseFile Unity_v2018.x.ulf -batchmode -nographics -quit || exit 0
      env:
        CYPHER_KEY: ${{ secrets.cypherkey }}

    - name: Build unitypackage
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath "UniNativeLinq-EditorExtension-Test" -executeMethod ExecuteMethods.CreateUnityPackage
        
    - name: Build unitypackage
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath "UniNativeLinq-EditorExtension-Test" -executeMethod ExecuteMethods.CreateSettingUnityPackage

    - uses: actions/upload-artifact@master
      with:
        path: artifact_unity
        name: unitypackage
        
    - uses: actions/upload-artifact@master
      with:
        path: artifact_setting
        name: unitypackage_setting

    - name: Clean
      run: |
        rm -rf artifact
        mkdir artifact
        cd UniNativeLinq-EditorExtension-Test/Assets # UniNativeLinq-EditorExtension-Test/Assets
        rm -f Tests.meta
        rm -rf Tests
        cp -f -a "../Data~/$TEST/Settings" Plugins/UNL/
      env:
        TEST: FULL

    - name: Create DLL
      run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath "UniNativeLinq-EditorExtension-Test" -executeMethod ExecuteMethods.CreateDll || exit 0

    - name: Copy DLL
      run: |
        ls -l UniNativeLinq-EditorExtension-Test/Assets/Plugins/UNL/Settings/
        ls -l UniNativeLinq-EditorExtension-Test/Assets/Plugins/UNL/
        ls -l UniNativeLinq-EditorExtension-Test/Assets/Plugins/
        ls -l UniNativeLinq-EditorExtension-Test/Assets/
        cp -f "UniNativeLinq-EditorExtension-Test/Assets/Plugins/UNL/Settings/UniNativeLinq.dll" "artifact/UniNativeLinq.dll"

    - uses: actions/upload-artifact@master
      with:
        path: artifact
        name: FULL

  pushJob:
    runs-on: ubuntu-latest
    needs:
    - createDllJob
    steps:
    - run: echo $netrc > ~/.netrc
      env:
        netrc: ${{ secrets.netrc }}
    - run: git clone https://github.com/pCYSl5EDgo/UniNativeLinq-EditorExtension-Test
    - run: git clone https://github.com/pCYSl5EDgo/UniNativeLinq-EditorExtension
    - name: Copy
      run: |
        rm -fr UniNativeLinq-EditorExtension-Test/Plugins/UNL/Settings/
        rm -fr UniNativeLinq-EditorExtension/UNL/
        cp -fr UniNativeLinq-EditorExtension-Test/Assets/Plugins/UNL/ UniNativeLinq-EditorExtension/UNL/
        mkdir pack
    
    - uses: actions/download-artifact@master
      with:
        name: unitypackage_setting
        path: pack
    
    - name: Commit & Push
      run: |
        cp -f pack/UniNativeLinq-Settings.unitypackage UniNativeLinq-EditorExtension/UNL/Packages/UniNativeLinq-Settings.unitypackage
        cd UniNativeLinq-EditorExtension
        rm -fr UNL/Settings/
        rm -f UNL/Settings.meta
        git config --global user.email "pcysl5edgo@yahoo.co.jp"
        git config --global user.name "pCYSl5EDgo"
        git add .
        git commit -a -m "[update]DLL Update of $GITHUB_SHA" || exit 0
    - run: |
        cd UniNativeLinq-EditorExtension
        git push -v || exit 0
